<a href="https://colab.research.google.com/github/josh1478/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Coding Activity 3 



In [16]:
#Python programing that applies inverse and transpose
import numpy as np
A = np.array([[3,2],[1,0]])
print(A)
inverse = (np.linalg.inv(A))
print(inverse)

[[3 2]
 [1 0]]
[[ 0.   1. ]
 [ 0.5 -1.5]]


In [14]:
B = np.dot(A,inverse)
print(B)

[[ 1.00000000e+00  0.00000000e+00 -5.55111512e-17]
 [-1.66533454e-16  1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [18]:
#Python Programming to Transpose a 3x3 Matrix A 
#Showing below how to transpose the value in the array
A = np.array([[3,4,3],[8,-4,9],[7,5,6]])
print(A)
B = np.transpose(A)
print(B)

[[ 3  4  3]
 [ 8 -4  9]
 [ 7  5  6]]
[[ 3  8  7]
 [ 4 -4  5]
 [ 3  9  6]]


In [19]:
#Python Programming to Inverse a 3x3 Matrix A 
#Showing below how to inverse the value in the array
A = np.array([[3,4,3],[8,-4,9],[7,5,6]])
print(A)
inverse = (np.linalg.inv(A))
print(inverse)

[[ 3  4  3]
 [ 8 -4  9]
 [ 7  5  6]]
[[-1.21052632 -0.15789474  0.84210526]
 [ 0.26315789 -0.05263158 -0.05263158]
 [ 1.19298246  0.22807018 -0.77192982]]
