<a href="https://colab.research.google.com/github/josh1478/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Final Exam

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [14]:
import numpy as np 
#To get how much money each student have. 
#([[1, 1, 1], #co-efficients from left hand side of eq - i
#[-1, 0, 1], co-efficients from left hand side of eq - iv
#[0, 1, -3]]) co-efficients from left hand side of eq - v
#([89, 6, 0]) #right hand side values of eq - i, iv and v
#Now we can now solve the using "np.linalg.inv(ecq).dot(ecq)"
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [12]:
# Unable to solve due to values are the same if we solve this equation it will have an error 

Problem 3. Consider the matrix, (40 points)
Find the eigenvalue/s
Find the eigenvectors

In [5]:
#To get the Eigenvalue and Eigenvectors is i used "np.linalg.eig"
A = np.array ([[8,5,-6],[-12,9,12],[-3,-3,5]])
print(A)

W,V = np.linalg.eig(A) 
print("The Eigenvalue/s is/are: ",W)
print("The right eigenvectors are:",V)
#X = V.round()
#print(X)

[[  8   5  -6]
 [-12   9  12]
 [ -3  -3   5]]
The Eigenvalue/s is/are:  [10.+9.74679434j 10.-9.74679434j  2.+0.j        ]
The right eigenvectors are: [[-6.19826768e-02-0.44653265j -6.19826768e-02+0.44653265j
   7.07106781e-01+0.j        ]
 [ 8.56977879e-01+0.j          8.56977879e-01-0.j
  -1.66861154e-16+0.j        ]
 [ 9.43214647e-03+0.24953295j  9.43214647e-03-0.24953295j
   7.07106781e-01+0.j        ]]
