<a href="https://colab.research.google.com/github/josh1478/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Midterm Exam

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [ ]:
import numpy as np
# To create a 5 lenght square matrix i've created a random array
x = np.array ([[5,4,1,12,13],[10,9,4,3,1],[10,13,15,14,15],[31,32,33,34,35],[41,42,43,44,45]])
print(x) 

[[ 5  4  1 12 13]
 [10  9  4  3  1]
 [10 13 15 14 15]
 [31 32 33 34 35]
 [41 42 43 44 45]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [ ]:
#To display a diagonal zero where i create a upper triangle "np.triu"
A = np.triu([[4,5,6],[9,8,4],[1,2,3]])
print(A)

[[4 5 6]
 [0 8 4]
 [0 0 3]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [ ]:
# To display a symmetrical i've use transpose
Z = np.array ([[2,3,1],[6,5,4],[9,8,7]])
print(Z)
print(np.transpose(Z))

[[2 3 1]
 [6 5 4]
 [9 8 7]]
[[2 6 9]
 [3 5 8]
 [1 4 7]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [ ]:
# To create a inverse for the given question
A = np.array([[1,2,3], [2,3,3],[3,4,-2]])
B = np.linalg.inv(A)
print(A)
print(B)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [ ]:
# To find the determinant i've just replace the "inv" to "det"
A = np.array([[1,2,3], [2,3,3],[3,4,-2]])
B = np.linalg.det(A)
print(A)
print(B)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

In [23]:
# To find the roots enter the first given number and let the program solve it. 
C = np.array ([[5,4,1],[10,9,4],[10,13,15]])
D = np.array ([3.4,8.8,19.2])
E = np.linalg.solve(C,D)
print(C)
print(D)
print(E)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[ 3.4  8.8 19.2]
[0.2 0.4 0.8]
