<a href="https://colab.research.google.com/github/josh1478/Linear-Algebra-58020/blob/main/Phython_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector spaces and its operation

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is', A)
print('Vector A is', B)


Vector A is [4 3]
Vector A is [ 2 -5]


In [12]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1,ball2])
print(pool.shape)
print(pool.size)
print(pool.ndim)

(2, 3)
6
2


##Vector addition

In [13]:
R = A+B
print(R)

[ 6 -2]


In [16]:
R = np.add(A,B)
R

array([ 6, -2])

##Vector Subraction

In [17]:
R = np.subtract(A,B)
R

array([2, 8])

##Vector scaling

In [22]:
A = np.array ([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [23]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


##Vector cross product

In [30]:
#initialize arrays
A = np.array([2,3,4])
B = np.array([1,7,0])
#compute for cross product

output = np.cross(A,B)
print(output)

[-28   4  11]


In [32]:
output = np.dot(A,B)
print(output)

23
