<a href="https://colab.research.google.com/github/josh1478/Linear-Algebra-58020/blob/main/Practical_Lab_exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical Lab exam 1

Probelm 1

In [24]:
import numpy as np
#a.WY
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
output = np.dot(W,Y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [7]:
#b.Z+Z
Z = np.array ([[0,1],[2,3]])
Z = np.array ([[0,1],[2,3]])
print(Z+Z)

[[0 2]
 [4 6]]


In [20]:
#c.3X
x = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
print(3*x)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2

In [60]:
#a. The product (YW)2 is not defined
YW = np.dot (Y,W)
n = ('FALSE')
print(np.square(YW))
print(n)

[[25 49]
 [16 16]]
FALSE


In [52]:
#b. WY – X 
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
x = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
o = np.dot(W,Y)
m = ('TRUE')
print(o-x)
print(m)


[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
TRUE


In [51]:
 #YW – Z2 
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
Z = np.array ([[0,1],[2,3]])
o = np.dot(Y,W)
h = ('TRUE')
print(o-Z*Z)
print(h)



[[ 5 -8]
 [ 0 -5]]
TRUE
