<a href="https://colab.research.google.com/github/josh1478/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations

In [23]:
import numpy as np
#Sum A+B
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [24]:
#Subtraction A-B
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [25]:
#subraction B-B
a = np.array ([[6,-3],[2,3]])
b = np.array ([[6,-3],[2,3]])
print(a-b)

[[0 0]
 [0 0]]
